### ISSUE TITLE
Disable the button

### ISSUE THREAD

**Issue by ibbatta** [ziscloud/angular-bootstrap-toggle#4]
Is there a way to disable the toggle?

**Comment by scmaverick** [comment]
I believe this angular implementation of the boots toggle doesnt actually include an input type checkbox within, it will just update angular variables directly, in such case the disabled behavior must be emulated somehow, I tried adding ng-disabled but it didn't work. Would we have any news?

**Comment by fdbva** [comment]
I can´t get it disabled either. Any tips or workaround? Thanks,

**Comment by nthnmldr** [comment]
Below is what I did.  It's a quick way to use ng-disabled.  There is a little cleaning up to do but this got me started.  

1. Add ngDisabled as property in the toggleConfig constant
```javascript
      /**
       * Type: boolean
       * Default: false
       * Description: Uses the angular ng-disabled attribute to disable/enabled the toggle.
       */
      ngDisabled: false
```
2. Add ngDisabled to the forEach loop of attribute configuration
```javascript
          // Configuration attributes
          angular.forEach(['on', 'off', 'size', 'onstyle', 'offstyle', 'style', 'ngDisabled'], function (key, index) {
            self[key] = angular.isDefined($attrs[key]) ?
              (index < 6 ? $interpolate($attrs[key])($scope.$parent) : $scope.$parent.$eval($attrs[key])) :
              toggleConfig[key];
          });
```
3. Add a $scope variable assignment to the bottom of the computeStyle function
```javascript
            $scope.disabled = self.ngDisabled;
```
4. Add ngDisabled as a watchable attribute
```javascript
          angular.forEach(['ngDisabled'], function (key) {
              var watch = $scope.$parent.$watch($attrs[key], function (value) {
                  if (self.ngDisabled !== value) {
                      self.ngDisabled = value;
                      self.computeStyle();
                  }
              });
              $scope.$parent.$on('$destroy', function () {
                  watch();
              });
          });
```
5. Change the onSwitch function to check disabled and only run if not
```javascript
          $scope.onSwitch = function (evt) {
              if (!$scope.disabled) {
                  ngModelCtrl.$setViewValue(!ngModelCtrl.$viewValue);
                  ngModelCtrl.$render();
              }
          };
```
6. Add the ngDisabled attribute to the elements in the template html
```javascript
          template: '<div class="toggle btn" ng-class="wrapperClass" ng-style="wrapperStyle" ng-click="onSwitch()" ng-disabled="disabled">' +
          '<div class="toggle-group">' +
          '<label class="btn" ng-class="onClass" ng-disabled="disabled"></label>' +
          '<label class="btn active" ng-class="offClass" ng-disabled="disabled"></label>' +
          '<span class="btn btn-default" ng-class="handleClass" ng-disabled="disabled"></span>' +
          '</div>' +
          '</div>'
```
7. Add ng-disabled="<your expression>" to your toggle element

**Issues**
1. The computeStyle function keeps growing the width of the toggle by about 9px every time it's called. My On and Off label widths change in value but the width doesn't change by much so I just saved the initial width and height to `self` after the wrapper width and height were calculated.  Then every subsequent computeStyle would start with those values.
```javascript
            self.width = wrapperComputedWidth;
            self.height = wrapperComputedHeight;
```
 2. The default bootstrap disabled styling uses opacity so when the toggle is disabled, you can faintly see the other hidden toggle option text if that label is longer than the width of the toggle.  I noticed this in testing, but in my case I don't care since my real values won't ever be long enough, but something of which to be aware.

**Comment by Asscobara** [comment]
That's great, thank you for this post.
